name: example
description: Runnable examples for the team_logger package.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  ansi_escape_codes: ^4.0.1
  clock: ^1.1.1
  format: ^4.1.0
  freezed_annotation: ^3.1.0
  stack_trace: ^1.12.1
  team_logger:
    path: ../

dev_dependencies:
  build_runner: ^2.15.0
  freezed: ^3.0.0-0.0.dev
  lints: ^5.0.0
