name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.0

dependencies:
  freezed_annotation: ^3.1.0
  equatable: ^2.0.8
  path: ^1.9.0
  team_logger:
    path: ../
  stack_trace: ^1.12.1
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.15.0
  freezed: ^3.2.5
  lints: ^6.0.0
  test: ^1.25.6
