name: team_logger
description: A logging library for big teams, big applications and huge logs.
version: 0.1.45
repository: https://github.com/vi-k/team_logger

environment:
  sdk: ^3.6.0

dependencies:
  ansi_escape_codes: ^3.1.2
  clock: ^1.1.2
  format: ^1.6.0
  logger_builder: ^0.3.1
  meta: ^1.16.0
  stack_trace: ^1.12.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
